openapi: 3.0.1
info:
  title: demo
  version: "1.0"
servers:
- url: http://localhost:12000
security:
- jwt: []
paths:
  /npl/demo/-/openapi.json:
    get:
      operationId: _getOpenAPI
      responses:
        "200":
          description: The OpenAPI spec
          content:
            application/json:
              schema:
                type: object
      security: []
  /npl/demo/HelloWorld/:
    get:
      operationId: _getHelloWorldList
      parameters:
      - name: page
        in: query
        required: false
        schema:
          minimum: 1
          type: integer
      - name: pageSize
        in: query
        required: false
        schema:
          maximum: 100
          minimum: 1
          type: integer
          default: 25
      - name: includeCount
        in: query
        description: "Include `totalItems` and `totalPages` in the response if set.\
          \ This option is very expensive, so should be avoided when possible."
        required: false
        schema:
          type: boolean
          default: false
      - $ref: "#/components/parameters/API_Version"
      - $ref: "#/components/parameters/NPL_Tag"
      responses:
        "200":
          description: All accessible protocol instances of this type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloWorld_List"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "500":
          $ref: "#/components/responses/500"
    post:
      operationId: _createHelloWorld
      parameters:
      - $ref: "#/components/parameters/API_Version"
      - $ref: "#/components/parameters/NPL_Tag"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HelloWorld_Create"
        required: true
      responses:
        "200":
          description: The new protocol instance
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloWorld"
        "204":
          description: No Content
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "500":
          $ref: "#/components/responses/500"
  /npl/demo/HelloWorld/{id}/:
    get:
      operationId: _getHelloWorldByID
      parameters:
      - $ref: "#/components/parameters/ProtocolID"
      - $ref: "#/components/parameters/API_Version"
      - $ref: "#/components/parameters/NPL_Tag"
      responses:
        "200":
          description: The protocol instance with this ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelloWorld"
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
  /npl/demo/HelloWorld/{id}/sayHello:
    post:
      operationId: HelloWorld_sayHello
      parameters:
      - $ref: "#/components/parameters/ProtocolID"
      - $ref: "#/components/parameters/API_Version"
      - $ref: "#/components/parameters/NPL_Tag"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: string
        "204":
          description: No Content
        "400":
          $ref: "#/components/responses/400"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "500":
          $ref: "#/components/responses/500"
components:
  schemas:
    _Party:
      required:
      - claims
      type: object
      properties:
        claims:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
      example:
        claims:
          preferred_email:
          - john.doe@example.com
    _Period:
      required:
      - days
      - months
      - weeks
      - years
      type: object
      properties:
        days:
          type: integer
        weeks:
          type: integer
        months:
          type: integer
        years:
          type: integer
    _Error:
      type: object
      properties:
        errorType:
          type: string
        id:
          type: string
          format: uuid
        idType:
          type: string
        message:
          type: string
        error:
          type: string
          nullable: true
        origin:
          type: object
          properties:
            value:
              type: string
            code:
              type: integer
              format: int32
            originType:
              type: string
            id:
              type: string
            message:
              type: string
          nullable: true
        stackTrace:
          type: string
          nullable: true
        clientStackTrace:
          type: array
          nullable: true
          items:
            type: object
            properties:
              name:
                type: string
              protocolId:
                type: string
                format: uuid
                nullable: true
              elementType:
                type: string
              location:
                type: object
                properties:
                  file:
                    type: string
                  line:
                    type: integer
                    format: int32
                  sourceRef:
                    type: object
                    properties:
                      path:
                        type: string
                      commit:
                        type: string
                    nullable: true
            nullable: true
    HelloWorld:
      required:
      - '@actions'
      - '@id'
      - '@parties'
      - '@state'
      type: object
      properties:
        '@id':
          type: string
          format: uuid
        '@parties':
          $ref: "#/components/schemas/HelloWorld_Parties"
        '@actions':
          $ref: "#/components/schemas/HelloWorld_Actions"
        '@state':
          $ref: "#/components/schemas/HelloWorld_States"
      readOnly: true
    HelloWorld_Parties:
      required:
      - greeter
      type: object
      properties:
        greeter:
          $ref: "#/components/schemas/_Party"
    HelloWorld_Actions:
      type: object
      properties:
        sayHello:
          type: string
          format: uri
          example: http://localhost:12000/npl/demo/HelloWorld/1ee39a43-8e4e-4b3b-8f1f-1e11ad495436/sayHello
    HelloWorld_List:
      required:
      - items
      type: object
      properties:
        '@prev':
          type: string
          format: uri
          example: http://localhost:12000/npl/demo/HelloWorld/?page=1&pageSize=10
        '@next':
          type: string
          format: uri
          example: http://localhost:12000/npl/demo/HelloWorld/?page=3&pageSize=10
        items:
          type: array
          items:
            $ref: "#/components/schemas/HelloWorld"
        page:
          type: integer
        totalItems:
          type: integer
          description: Total number of accessible protocol instances. Only included
            if the `includeCount` query parameter was set.
          nullable: true
        totalPages:
          type: integer
          description: Total number of accessible pages. Only included if the `includeCount`
            query parameter was set.
          nullable: true
    HelloWorld_Create:
      required:
      - '@parties'
      type: object
      properties:
        '@parties':
          $ref: "#/components/schemas/HelloWorld_Parties"
    HelloWorld_States:
      type: string
      enum:
      - greeting
      - greeted
  responses:
    "400":
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/_Error"
    "401":
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/_Error"
    "403":
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/_Error"
    "404":
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/_Error"
    "500":
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/_Error"
  parameters:
    API_Version:
      name: X-NPL-API
      in: header
      description: Optional parameter to require a specific API version
      required: false
      schema:
        type: string
    NPL_Tag:
      name: X-NPL-TAG
      in: header
      description: Optional parameter to require a specific NPL Tag
      required: false
      schema:
        type: string
    ProtocolID:
      name: id
      in: path
      required: true
      schema:
        type: string
        format: uuid
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
